name: Discord GitHub Push Webhook

on:
  push:
    branches:
      - main

jobs:
  send_to_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          REPO_NAME: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
          AUTHOR_AVATAR: https://github.com/${{ github.actor }}.png
        run: |
          commits=$(jq -c '.commits[]?' "$GITHUB_EVENT_PATH" || echo "")
          if [ -z "$commits" ]; then
            echo "No commits found, exiting."
            exit 0
          fi

          count=$(echo "$commits" | wc -l)

          echo "$commits" | while IFS= read -r commit; do
            COMMIT_MSG=$(echo "$commit" | jq -r '.message')
            COMMIT_URL=$(echo "$commit" | jq -r '.url')
            COMMIT_HASH=$(echo "$commit" | jq -r '.id' | cut -c1-7)
            AUTHOR_NAME=$(echo "$commit" | jq -r '.author.name')

            payload=$(cat <<EOF
{
  "username": "GitHub",
  "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
  "embeds": [{
    "author": {
      "name": "${AUTHOR_NAME}",
      "icon_url": "${AUTHOR_AVATAR}"
    },
    "title": "[${REPO_NAME##*/}:${BRANCH_NAME}] ${count} new commit(s)",
    "url": "${COMMIT_URL}",
    "color": 7506394,
    "description": "```$COMMIT_HASH```\n${COMMIT_MSG} – ${AUTHOR_NAME}"
  }]
}
EOF
            )

            curl -s -H "Content-Type: application/json" \
              -X POST \
              -d "$payload" \
              "$DISCORD_WEBHOOK"
          done
